steps:
# Build the container image with a timestamp tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/plantkeepers-backend:latest', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/plantkeepers-backend:latest']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'plantkeepers-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/plantkeepers-backend:latest'
  - '--region' 
  - 'europe-west1' 
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--port'
  - '8000'

images:
- 'gcr.io/$PROJECT_ID/plantkeepers-backend:latest'
