# Generated by Django 5.2 on 2025-05-02 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_id", models.CharField(max_length=255)),
                ("ad_network", models.CharField(default="AdMob", max_length=100)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_banner", "Home Banner"),
                            ("plant_detail", "Plant Detail Page"),
                            ("care_tips", "Care Tips Section"),
                            ("settings", "Settings Page"),
                        ],
                        max_length=50,
                    ),
                ),
                ("impression_time", models.DateTimeField(auto_now_add=True)),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=255)),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time",
                    models.IntegerField(help_text="Response time in milliseconds"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click_time", models.DateTimeField(auto_now_add=True)),
                (
                    "impression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="plant_api.adimpression",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantCare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "water_frequency",
                    models.IntegerField(help_text="Watering frequency in days"),
                ),
                (
                    "light_requirements",
                    models.CharField(
                        help_text="Light requirements (e.g., Full sun, Partial shade)",
                        max_length=100,
                    ),
                ),
                (
                    "humidity_level",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "temperature_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fertilizer_frequency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("care_summary", models.TextField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "plant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care",
                        to="plant_api.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WateringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_watered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_watering_due", models.DateTimeField()),
                ("is_watered", models.BooleanField(default=False)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watering_schedules",
                        to="plant_api.plant",
                    ),
                ),
            ],
        ),
    ]
