# Generated by Django 5.2 on 2025-05-02 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0003_user_alter_userplant_id_alter_userplant_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wateringschedule",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watering_schedules",
                to="plant_api.userplant",
            ),
        ),
    ]
