# Generated by Django 5.2 on 2025-05-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0004_alter_wateringschedule_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
