# Generated by Django 5.2 on 2025-05-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
