# Generated by Django 5.2 on 2025-05-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0006_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wateringschedule",
            old_name="plant",
            new_name="user",
        ),
    ]
