# Generated by Django 5.2 on 2025-05-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_api", "0007_rename_plant_wateringschedule_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("banner", "Banner Ad"),
                            ("interstitial", "Interstitial Ad"),
                            ("rewarded", "Rewarded Ad"),
                            ("native", "Native Ad"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("home_banner", "Home Banner"),
                            ("plant_detail", "Plant Detail Page"),
                            ("care_tips", "Care Tips Section"),
                            ("settings", "Settings Page"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "unit_id_android",
                    models.CharField(
                        help_text="AdMob ad unit ID for Android", max_length=255
                    ),
                ),
                (
                    "unit_id_ios",
                    models.CharField(
                        blank=True,
                        help_text="AdMob ad unit ID for iOS",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_test",
                    models.BooleanField(
                        default=True, help_text="Is this a test ad unit?"
                    ),
                ),
                (
                    "refresh_rate",
                    models.IntegerField(
                        default=60,
                        help_text="Ad refresh rate in seconds (for banner ads)",
                    ),
                ),
                (
                    "targeting_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Keywords for ad targeting",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="adclick",
            name="conversion_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="adclick",
            name="conversion_value",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="device_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="device_platform",
            field=models.CharField(default="android", max_length=20),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="is_test_ad",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ad_impressions",
                to="plant_api.user",
            ),
        ),
        migrations.AddField(
            model_name="adimpression",
            name="ad_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impressions",
                to="plant_api.adunit",
            ),
        ),
        migrations.CreateModel(
            name="AdRevenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("impressions", models.IntegerField(default=0)),
                ("clicks", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                (
                    "ecpm",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Effective Cost Per Mille",
                        max_digits=10,
                    ),
                ),
                (
                    "fill_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Ad fill rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "ad_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue",
                        to="plant_api.adunit",
                    ),
                ),
            ],
            options={
                "unique_together": {("ad_unit", "date")},
            },
        ),
    ]
