# Generated by Django 5.2 on 2025-05-24 15:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plant_api", "0008_adunit_adclick_conversion_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdKpi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("active_users", models.IntegerField(default=0)),
                ("total_impressions", models.IntegerField(default=0)),
                ("impressions_per_user", models.FloatField(default=0.0)),
                (
                    "estimated_revenue",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                (
                    "estimated_arpu",
                    models.DecimalField(
                        decimal_places=6,
                        default=0.0,
                        help_text="Average Revenue Per User",
                        max_digits=10,
                    ),
                ),
                (
                    "target_achieved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether target of 50 impressions per user was achieved",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "last_active_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("session_count", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="plant_api.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
