# Generated by Django 5.2 on 2025-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0009_adkpi_activeuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="UID",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the User",
                max_length=500,
                unique=True,
            ),
        ),
    ]
