# Generated by Django 5.2 on 2025-05-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_api", "0011_alter_plant_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="UID",
            field=models.CharField(
                help_text="Unique identifier for the User", max_length=500, null=True
            ),
        ),
    ]
