# Generated by Django 5.2 on 2025-05-31 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0012_alter_plant_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adimpression',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wateringschedule',
            name='user',
        ),
        migrations.AddField(
            model_name='activeuser',
            name='uid',
            field=models.CharField(help_text='Firebase UID to identify the user', max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='activeuser',
            unique_together={('uid', 'date')},
        ),
        migrations.RemoveField(
            model_name='plant',
            name='UID',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='scientific_name',
        ),
        migrations.RemoveField(
            model_name='plantcare',
            name='plant',
        ),
        migrations.AddField(
            model_name='adimpression',
            name='uid',
            field=models.CharField(help_text='Firebase UID to identify the user', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='care',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plant_api.plantcare'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantcare',
            name='name',
            field=models.CharField(default='Unknown', help_text='Common name of the plant species', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcare',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Custom name for the plant given by the user', max_length=255),
        ),
        migrations.AlterField(
            model_name='plantcare',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserPlant',
        ),
        migrations.DeleteModel(
            name='WateringSchedule',
        ),
        migrations.RemoveField(
            model_name='activeuser',
            name='user',
        ),
        migrations.AddField(
            model_name='plant',
            name='uid',
            field=models.CharField(help_text='Firebase UID to identify the user', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
