# Generated by Django 5.2 on 2025-06-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_api', '0013_remove_adimpression_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
